### ISSUE TITLE
LOAD MORE bps button is only loading certains bps

### ISSUE THREAD

**Issue by JustinCast** [eoscostarica/eos-rate#550] opened 2021-05-05 23:10 UTC

**Comment by JustinCast** [comment] 2021-05-07 21:58
It seems that sometimes (depending on which branch are positioned), you got some errors when building the container to run the project locally.
docker system prune maybe help with that. Also be sure of having set the proper env values to avoid this undesired behavior.

**Comment by leisterfrancisco** [comment] 2021-07-30 19:30
Couldn't reproduce error, I'm gonna close it for now until exist a better error description

**Closed by leisterfrancisco** 2021-07-30 19:30 UTC
Labels: bug
